- pyunifiprotect/unifi_protect_server.py
The X-CSRF-Token header would be uppercase so
a get is needed in order for it to be found
Remove references to urllib3 since aiohttp
is used now instead.
> Fix UDMP detection

- pyunifiprotect/unifi_protect_server.py
Initial Support for a WebSocket connection. It looks like only motion events are available for this interface.
It looks like an additional WebSocket connection is used by the Unifi Protect web interface that may expose doorbell rings, but the messages are binary, so this will have to suffice for now.
Things I'm not sure about:
- WebSocket connection lifecycle: I've not tested unexpected disconnects, timeouts, etc., and recovering from those events.
- Are changes required in https://github.com/briis/unifiprotect to take advantage of the new real-time updates for motion events?
> added websocket connection for motion events

- pyunifiprotect/unifi_protect_server.py
I'm not sure what causes this, but one of my cameras was using my public IP instead of the NVR hostname/ip for RTSP streams. This ensures the proper ip/hostname is set when streaming via RTSP by setting it to the NVR.
I don't believe there to be any negative side effects of this change, as I believe all RTSP streams are routed through the NVR and not direct to the camera.
> use nvr host for rtsp stream

- pyunifiprotect/unifi_data.py
- pyunifiprotect/unifi_protect_server.py
Uses the `lastMotion` and `isMotionDetected` events to construct the camera event update.
Verified it switches back to using `events` which gets us scores etc when recording is turned back on.
> Add support for motion detection when recording is off

- pyunifiprotect/unifi_data.py
- pyunifiprotect/unifi_protect_server.py
I added `has_camera` to the state machine so we can skip cameras that aren't present.
> Skip cameras that are not present in the state machine

- pyunifiprotect/unifi_data.py
- pyunifiprotect/unifi_protect_server.py
This assumes that events are always generated for light motion detection and we do not need to
create them from the light model like we do for cameras when motion detection is disabled.
> Simplify light processing

- .github/workflows/ci.yaml
- pyunifiprotect/unifi_data.py
- pyunifiprotect/unifi_protect_server.py
Maybe fixes https://github.com/briis/unifiprotect/issues/225
>  Only clear the event_object if smartDetectEvents is not set in the followup motion event

- pyunifiprotect/__init__.py
- pyunifiprotect/__main__.py
- pyunifiprotect/cli.py
- pyunifiprotect/exceptions.py
- pyunifiprotect/unifi_data.py
- tests/test_unifi_protect_server.py
* Removes all exceptions to new module `pyunifiprotect.exceptions`
* Adds new base classes for exceptions
* Cleans up imports from `pyunifiprotect` to be relative
* Adds new class enum `ModelType` to for `modelKey` values
* Adds refactors decoding of packets from Unifi Protect into new classes: `WSPacketFrameHeader`, `WSPacketFrame`, and `WSPacket`
* These classes will give a more structured approach to handling packets from Protect
* Basic support for updating/creating new Protect packets
* Adds a test to make sure `decode_ws_frame` stays consistent / working
> Refactors packet code

- .github/workflows/ci.yaml
* Updates `lint` / `black` / `isort` job steps to only run on Python 3.9 since that is how tox is configured
* Adds `py38` / `py39` tox env runs
> Adds missing pytest env for tox

- pyunifiprotect/unifi_protect_server.py
`_last_device_update_time` and `_last_websocket_check` are actually used as reference points since the last time we did something rather then absolute markers in time. So `time.monotonic` is actually what is wanted here since we absoltely do not want time to move backwards on us.
`time.time` is actually subject to NTP updates. So you could call `time.time` twice in a row and get a time before the one you got when you previously called it.
`time.monotonic` never changes. It will always "X second python has been running".
https://docs.python.org/3/library/time.html#time.monotonic
> Switch time.time -> time.monotonic

- pyunifiprotect/unifi_protect_server.py
Fixes a race condition / random bug introduced by changing from `time.time` to `time.monotonic` by actually getting the diff between the last check markers and the current monotonic clock.
The issue was since the monotonic clock is not real time, it can start at 0 and be a number less then the check intervals. So if `current_time = 30`, the `(current_time - WEBSOCKET_CHECK_INTERVAL_SECONDS) > self._last_websocket_check` would fail and the Websocket would never be connected.
> Fixes inconsistencies with setting up websocket

- pyproject.toml
- requirements_all.txt
- requirements_test.txt
- setup.cfg
- tox.ini
More of me spliting code out of my "more tests" branch. 
Would there be any interest in using something like Coveralls or CodeCov? I think @briis would need to set that up, but it would be a good time to add it though. 
* Adds coverage reporting on CI. 
* Adds pytest-sugar
* Updates linters to also lint test files
> Testing Improvements

- pyunifiprotect/test_util/__init__.py
- pyunifiprotect/unifi_protect_server.py
- pyunifiprotect/utils.py
* Adds new method to try to retrieve error from response body when there is a bad error code instead of always using `response.reason`, which will always be the "name" of the HTTP status code (500 = Internal Server Error, 400 = Bad Request, etc.)
* Handles error response in `write_image_file` for generating sample data
> Improves determining reason for bad responses

- pyunifiprotect/test_util/__init__.py
- tests/sample_data/sample_constants.json
- tests/test_unifi_protect_server.py
Test failure found from latest test run against live data: https://github.com/AngellusMortis/pyunifiprotect/runs/3708943132
> Fixes tests if test camera is offline

- pyunifiprotect/unifi_protect_server.py
If you are using `pyunifiprotect` _on_ the same physical machine as your UnifiOS console, UnifiOS does not provide a CSRF token. `aiohttp` cannot handle a header with a `NoneType` so this should exclude the CSRF token if it is not being provided by UnifiOS.
Fixes https://github.com/briis/pyunifiprotect/issues/33 and https://github.com/briis/unifiprotect/issues/312
```
git+https://github.com/AngellusMortis/pyunifiprotect.git@feature/no-csrf-token#pyunifiprotect==0.35.3
```
> Adds support for no CSRF token from UnifiOS

- pyunifiprotect/data/types.py
- tests/test_data.py
- tests/test_unifi_data.py
Fixes:
```
2021-10-30 00:36:57 ERROR (MainThread) [pyunifiprotect.unifi_protect_server] Error processing websocket message
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 282, in _setup_websocket
self._process_ws_message(msg)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 949, in _process_ws_message
self._process_event_ws_message(action_json, data_json)
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 1018, in _process_event_ws_message
device_id, processed_event = event_from_ws_frames(
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/unifi_data.py", line 466, in event_from_ws_frames
state_machine.add(event_id, …
```
> Fixes dictionary is empty error when trying to remove item from FixSizeOrderedDict

- mypy.ini
- pyproject.toml
- pyunifiprotect/__main__.py
- pyunifiprotect/cli.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- pyunifiprotect/data/websocket.py
- pyunifiprotect/exceptions.py
- pyunifiprotect/test_util/__init__.py
- pyunifiprotect/test_util/anonymize.py
- pyunifiprotect/unifi_data.py
- pyunifiprotect/unifi_protect_server.py
- pyunifiprotect/utils.py
- tests/conftest.py
- tests/sample_data/constants.py
- tests/test_unifi_protect_server.py
- tests/test_unifi_protect_server_old.py
- tests/test_unifi_protect_server_ws.py
Last dozy of a PR, I swear. 
Enables a lot more strict typing flags for mypy and adds the needed type hints everywhere.
The major changes outside of type hints:
* Adds defaults to various places we use `.get` on a dict
* Removes `raw` from `api_request` and splits that one call into four to help with typing: `api_request_raw` (returns `bytes`), `api_request` (returns `dict` | `list`), `api_request_obj` (returns `dict`) and `api_request_list` (returns `list`)
I can move these changes into smaller PRs, but for this, it might be better to just test everything all at once.
```
git+https://github.com/AngellusMortis/pyunifiprotect.git@feature/strict-mypy#pyunifiprotect==0.35.3
```
> Enforces strict mypy type checking

- pyproject.toml
- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
When trying to make everything be able to use construct, I kept running into issues with how I was handled child `ProtectBaseObject` attributes. This is a big refactor to start handling them all automatically instead of trying to manually manage them, which was a nightmare. 
This also supports attributes that have many child `ProtectBaseObject` values (lists / dicts) which there was no real support for before.
> Makes nested Protect Objects smarter

- pyunifiprotect/unifi_protect_server.py
- tests/test_unifi_protect_server.py
Related: https://github.com/briis/unifiprotect/issues/321
Because we currently log every time update is called that the WS disconnected after it has been disconnected for 60 seconds or more, there is no actual way to know if the log messages were valid or not. `.update` will only try to reconnect if there has been at least 120 seconds last attempt. So the logs could just be false positives.
This should change it so the warning log message only when a reconnect attempt is made. This should greatly reduce the log spam and only tell us when real reconnect attempts are made to help us debug not reconnecting better.
I also cleaned up and made both `.update` methods work basically the same as each other (I am the one that recommended using `monotonic` and then went and used datetimes in the new …
> Improves reconnect/logging logic for Websockets

- pyunifiprotect/unifi_protect_server.py
- setup.cfg
* Adds metadata needed so type hints are exported for the package when installed.
* Fixes args for `ProtectApiClient` so they appear in type hints correctly.
> Adds PEP 561 typing metadata

- mypy.ini
- pyproject.toml
- pyunifiprotect/data/__init__.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- pyunifiprotect/test_util/__init__.py
- pyunifiprotect/unifi_protect_server.py
- pyunifiprotect/utils.py
- requirements_all.txt
- requirements_test.txt
- setup.cfg
- tests/conftest.py
- tests/sample_data/sample_constants.json
- tests/test_data.py
- tests/test_unifi_protect_server.py
- tests/test_unifi_protect_server_ws.py
- tox.ini
The main goal of this is to remove Pydantic's hard runtime type enforcement when creating objects from JSON that comes from UFP. Runtime type enforcement will still be applied to manual updates to UFP objects. To enable type enforcement for UFP JSON, set the ENV `UFP_DEBUG=True`
* Removes `klass_from_dict` and `from_unifi_dict` out of `ProtectBaseObject` and made them separate methods.
* Changed `__init__` to not run `unifi_dict_to_dict`
* Adds `from_unifi_dict` that runs `unifi_dict_to_dict` and then chooses between `__init__` and `construct` based on ENV variable
* Adds support for construct generating the same object structure as `__init__`
* Adds `convert_unifi_data` to take a pydantic field and automatically convert the passed in value to the correct type (usually just passing the …
> Updates ProtectBaseObject to use construct instead of normal pydantic constructor

- .devcontainer/devcontainer.json
`defaultInterpreterPath` I thought was suppose to be a replacement for `pythonPath`, but `pythonPath` still exists, so have both to ensure no issues using VS Code setup.
> Adds pythonPath settings in devcontainer

- pyunifiprotect/api.py
- pyunifiprotect/data/__init__.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/bootstrap.py
- pyunifiprotect/data/websocket.py
- tests/test_api.py
- tests/test_api_polling.py
- tests/test_api_ws.py
The new subscriptions uses a new message class:
```python
class WSSubscriptionMessage:
action: WSAction
new_update_id: UUID
changed_data: Dict[str, Any]
new_obj: ProtectModel
old_obj: Optional[ProtectModel] = None
```
The fields are pretty straight forward:
* `old_obj` is `None` if `action` is `ADD`
* `old_obj` + `changed_data` = `new_obj` 
I am not a big fan of `changed_data` being a raw dict, but it is the already posted "cleaned" data so the keys match up with the attrs perfectly.
> Adds WS Subscriptions to new API Client

- pyunifiprotect/data/devices.py
- tests/conftest.py
- tests/test_data_updates.py
@briis I split this out into a sperate PR to help you out adding new features to `pyunifiprotect`. We will need to able to control the output volume for the camera speakers for the `media_player` entities.
* Helper methods to update the device goes on the device class (in this case a camera).
* I did a check for the feature flag that is required for the change to work (cannot change speaker volume if there are no speakers)
* After you update the device class, call `.save_device` which will diff the object and then call `ProtectApiClient.update_device` which will do the `PATCH` to for the device like `UvpServer` did.
* You can write a test that verifies the `PATCH` request is what you expected from reverse engineering the change.
* Input validation is automatically done by `pydantic` via …
> Adds set_speaker_volume to cameras

- .gitignore
- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/exceptions.py
- pyunifiprotect/stream.py
- requirements_all.txt
- requirements_test.txt
- setup.cfg
- tests/conftest.py
- tests/test_data.py
* Adds ability to exclude fields from "changed" data for UFP objects (override `_get_excluded_changed_fields`)
* Adds `FfmpegCommand`: ffmpeg wrapper class to run ffmpeg commands. 
* Adds `TalkbackStream`: extends `FfmpegCommand` to play an input to a camera
* Adds `play_audio` to camera obj that wraps `TalkbackStream`
`play_audio`, `FfmpegCommand`, and `TalkbackStream` all obviously requires `ffmpeg` to use.
The way to test locally is to use the `unifi-protect shell` command:
```python
c = protect.bootstrap.cameras[id_of_camera_with_speaker]
await c.play_audio(path_to_mp3_file)
```
> Adds ability to play audio from URL to a camera via talkback settings

- pyunifiprotect/api.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
Since we are not using Sphinx (and VS Codes not support Sphinx style docstrings), I have optimized all of the existing doc strings to work better in VS Code.
Before:
After:
:
> Optmize docstrings for VS Code

- pyunifiprotect/data/base.py
Some typing error started happening for python 3.9. This removes an unused attribute that is causing the issues.
> Fixes typing error

- pyunifiprotect/api.py
- pyunifiprotect/data/devices.py
* Removes the `dt` argument from `get_camera_snapshot` and `get_snapshot` as it does not function as expected. It looks like the `ts=` param  is _only_ used as a cache buster in UFP and does not actually function as a way to get a snapshot from a specific time.
I was never actually verifying that it worked quite as expected before. Just seeing it gave me an image.
> Removes the dt argument for generating snapshots

- pyunifiprotect/api.py
- pyunifiprotect/data/__init__.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/test_util/__init__.py
- pyunifiprotect/test_util/anonymize.py
- tests/conftest.py
- tests/sample_data/sample_event_smart_track.json
- tests/test_api.py
- tests/test_data.py
Implements https://github.com/briis/pyunifiprotect/issues/98. Everything except the last point about creating the image. 
The `ts=` query param for `camera/{id}/snapshot` did not work like I expected. See https://github.com/briis/pyunifiprotect/pull/100. The only other way I can think to implement that is to splice frames out of the video using ffmpeg, but the exported videos are not 100% accurate, so it could result into bad images.
*  `ProtectApiClient`: Adds passing API reference for `get_device` methods
*  `ProtectApiClient`: Adds `get_event` method
*  `ProtectApiClient`: Adds `get_event_smart_detect_track_raw` / `get_event_smart_detect_track` methods
* `.data`: Adds `SmartDetectTrack` and `SmartDetectItem` classes
* `Event`: Adds `get_smart_detect_track` and `get_smart_detect_zones`
> Adds retrieving the Smart Detect Track for a smart detection

- pyunifiprotect/api.py
- tests/conftest.py
- tests/test_api.py
Based on some WIP changes I saw @briis doing. Added some extra methods to grab data without connecting to Websocket.
* `ProtectApiClient`: Adds `get_nvr`
* `ProtectApiClient`: Adds `get_bootstrap`
> Adds get_bootstrap and get_nvr methods

- pyunifiprotect/data/bootstrap.py
- pyunifiprotect/unifi_protect_server.py
* `UpvServer`: Adds _connection_host for generating RTSP URLs for when UFP instance is behind a reverse proxy
* `ProtectApiClient`: Allows NVR object to be updated from WS
> Adds _connection_host for UpvServer

- pyunifiprotect/data/devices.py
- tests/test_data_updates.py
I am kind of torn on this one. I _think_ this is a new change in Protect that does not expose changing WDR when the camera has HDR. I have 1x G4 Bullet (HDR), 4x G4 Pros (HDR), and 1x G4 Doorbell (no HDR) and WDR _only_ appears on my G4 Doorbell now, in the Protect WebUI.
I remember changing the WDR for my G4 Pros previously, but it seems to have changed. It looks like changing WDR on an HDR camera does still have some effect (I see the lens do something, but the picture quality does not really change). So we may not want to enforce this, but if we want to stay inline with how Protect works...
> Requires no HDR to set WDR

- pyunifiprotect/api.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/bootstrap.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/types.py
- pyunifiprotect/data/websocket.py
- pyunifiprotect/utils.py
- tests/test_api_polling.py
- tests/test_api_ws.py
- tests/test_data_updates.py
* Adds option to force emit messages when an object is changed
* Ensures PATCH requests for updating an LCDMessage object is always what UFP is expecting:
* If no `resetAt` was passed in, it was defaulted to +1 minute
* If no `type` was passed in (for CUSTOM_MESSAGE -> CUSTOM_MESSAGE changes), the display would break
This one is to "fix" a bug in UFP. When you update a Viewer, it does not emit a WS message like updating other objects do. This will let you to pass `force_emit=True` on `save_device` to construct a fake WS message of the change.
This will allow downstream subscribers (like Home Assistant) to trigger updates properly in the absence of a real UFP message.
Other bundled changes/fixes for HA integration:
* `ProtectApiClient`: Ensure `start` param passed into `get_events` inside …
> Adds option to force emit messages when an object is changed

- .devcontainer/Dockerfile
- pyunifiprotect/api.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/bootstrap.py
- tests/test_api_ws.py
- tests/test_data.py
* Increases Bootstrap poll interval to 15 minutes if WS is activate. Does not need to be polled every 60 seconds
* Adds arguments to ignore a number of events from WS
* Adds test to benchmark processing Websocket packets
* Optimizes `update_from_dict` to not call `.copy` or `.construct`.
No optimization:
With optimizations: 
second pass optimizations: 
The `test_ws_filtered` is closer to what the HA performance gains should be. The only difference there is that NVR messages were ignored for that test to improve coverage. 
About a ~35% performance increase on the mean process time for the `update_from_dict` optimizations and then an additional 25% (52% total) increase filtering out WS messages.
> Optmizations for `ProtectApiClient`

- .github/workflows/release.yml
This workflow needs a PyPi API token secret added to use.
1. Go to https://pypi.org/manage/account/token/
2. Create a token for "Project: pyunifiprotect"
3. Go to https://github.com/briis/pyunifiprotect/settings/secrets/actions
4. Add "New repository secret" named `PYPI_API_TOKEN` with the value from above
> Creates release workflow

- pyunifiprotect/api.py
The `raise_exception` argument passed into the `api_request*` methods was not actually working because higher up the chain it was checking the status code first. 
This was causing the retry logic for the event thumbnails to fail.
> Fixes raise exception

- pyunifiprotect/api.py
- tests/test_api.py
Let's users match their `connection_host` to their `host`. Would allow access RTSP streams over the Internet.
> Adds option to override connection host

- pyunifiprotect/data/types.py
- tests/test_data.py
Fix for https://github.com/briis/unifiprotect/issues/428.
Makes it so if a direct match for enum is not found, fallback to a case incentive search
> Makes str enums case insensitive

- pyunifiprotect/api.py
- pyunifiprotect/cli.py
- tests/test_api.py
This should greatly improve the logging consistency for WS connects/disconnects. A "warning" message will be posted as soon as the WS disconnects and then an "info" message will be posted as soon as it reconnects. Also adds logging level to shell output.
Good way to test:
In VS Code Dev container:
1. Run `Subcommand: shell` debug task
2. Run the following code, it should simulate the HA update loop close enough:
```python
from pyunifiprotect import NvrError
force = False
while True:
try:
await protect.update(force=force)
except NvrError:
force = True
else:
force = False
await asyncio.sleep(5)
```
3. Update/downgrade UniFi Protect version (from UNVR cli, if you are doing beta version, you need to use UniFi OS WebUI):
```bash
apt-get install --reinstall --allow-downgrades …
```
> Improves logging around WS connects/disconnects

- pyunifiprotect/data/devices.py
- pyunifiprotect/stream.py
- tests/conftest.py
- tests/test_data.py
I realized that HA never updates the speaker state because UniFi Protect does not send WS messages about talkback. This will let us start playing audio, update speaker state and then block until completion so we can update speaker state again.
> Play audio without blocking until completion

- .vscode/launch.json
- pyunifiprotect/api.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/bootstrap.py
- pyunifiprotect/data/devices.py
- tests/test_api.py
- tests/test_api_ws.py
After testing more in my main HA install, I found some more issues. 
Issues:
* `emit_message` was not being awaited
* As a result of above ^ the triggers were very inconsistent
Changes:
* Use fixed point in future as when the event "ends". This let's look at the WS value for the 30 second cutoff, but still have the 3 second "auto-expire"
* No more datetime math for the `is_` property. 
* Improves WS reconnects in the event of a disconnect
Since I am kind of tired of making releases only to test in my prod install. I am going to directly install this branch in my prod HA and test it further before marking as read.
> Improves is_ attrs

- .devcontainer/devcontainer.json
- .vscode/launch.json
- pyproject.toml
- pyunifiprotect/api.py
- pyunifiprotect/test_util/__init__.py
- pyunifiprotect/websocket.py
- tests/conftest.py
- tests/test_api.py
- tests/test_api_polling.py
- tests/test_api_ws.py
This PR will be a breaking change and need a major version bump (3.0) as it changes a number of public access variables on `ProtectApiClient`. Even if they essentially still function the same. 
Completely refactors and redesigns Websocket code:
* All Websocket code is not pulled out into a new Websocket class
* Adds timeout to handle Websocket connection getting "stuck"
* Decreases reconnect time to 10 seconds
* Simplifies async logic: WS task and WS session are no longer tracked on the class level. The disappear as soon as they are no longer relevant.
* Simplifies `last_update_id` and ensures it is always updated for future reconnects
Unrelated: Fixes python-xdist running with using "run tests", but _not_ running when you "debug tests".
> Refactor Websocket code

- pyunifiprotect/data/devices.py
- pyunifiprotect/data/types.py
- pyunifiprotect/utils.py
Fixes https://github.com/home-assistant/core/issues/70257.
I tried to use decimals for camera zone coords, but it has really been proving difficult and not worth it for interop with UniFi Protect since it uses floats. This just removes all of the attempts at decimals and always uses floats to match UniFi Protect.
Technically a breaking change, but I will only do a minor version bump (3.4.0) for it since they are still "number-like" types and will likely not break any downstream code.
> Switch to floats for camera zone coords

- pyunifiprotect/utils.py
- requirements_all.txt
- requirements_test.txt
- setup.cfg
typer < 0.4.1 is not compatible with click >= 8.1.0. However, 0.4.1 should be compatible with both click < 8.10 and click >= 8.1.0.
Fixes https://github.com/home-assistant/core/issues/71422
> Require newer version of typer to ensure click compatbility

- pyunifiprotect/cli/__init__.py
- pyunifiprotect/cli/base.py
- pyunifiprotect/cli/nvr.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/utils.py
- setup.cfg
- tests/data/test_nvr.py
Start of adding a full CLI interface for the library.
* Moves shared CLI options to `unifi-protect` root command
* Technically a breaking change, but the CLI interface before this PR was only for CI and debugging. This is the start of stabilizing it. The preferred way is still via ENVs anyways.
* Refactors the root commands to use a context obj to initialize and share UniFi Protect instance
* Adds `nvr` command group that provides interfaces for interacting with `NVR` class (works great with `jq`)
* Fixes child `ProtectBaseObj` not being serialized correctly for `save_device`
> Adds NVR CLI interface

- README.md
- pyunifiprotect/cli/__init__.py
- pyunifiprotect/cli/base.py
- pyunifiprotect/cli/cameras.py
- pyunifiprotect/cli/chimes.py
- pyunifiprotect/cli/doorlocks.py
- pyunifiprotect/cli/light.py
- pyunifiprotect/cli/nvr.py
- pyunifiprotect/cli/sensors.py
- pyunifiprotect/cli/viewers.py
Adds the following commands for all adoptable device types. Some commands may be redundant/useless on some device types.
* base -  list all devices (full JSON list, basically the same thing as `/cameras`, `/lights`, etc. API endpoints)
* `list-ids` - list of ID: name of each device
* `[id]` - list full JSON for device, basically the same thing as `/cameras/{id}`, `/lights{id}`, etc. API endpoints)
* `{id} protect-url` - gets Web app management URL for device
* `{id} is-wired` - returns if device is wired (has active Wired connection)
* `{id} is-wifi` - returns if device is WiFi enabled (has WiFi antenna)
* `{id} is-bluetooth` - returns if device is Bluetooth enabled (pairs via a U6 AP using Bluetooth, such as Doorlock and Smart Sensor)
* `{id} bridge` - returns full JSON for the bridge …
> Adds common CLI commands for all UFP devices

- pyunifiprotect/cli/cameras.py
- pyunifiprotect/cli/doorlocks.py
- pyunifiprotect/cli/light.py
- pyunifiprotect/cli/liveviews.py
- pyunifiprotect/cli/nvr.py
- pyunifiprotect/cli/sensors.py
- pyunifiprotect/cli/viewers.py
- pyunifiprotect/data/__init__.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- tests/conftest.py
- tests/data/test_common.py
- tests/data/test_nvr.py
- tests/test_api.py
A bunch of updates from latest version of Protect backend
* Adds helper method/command to change current analytics for the NVR
* Adds a ton of enums for various fields
* Adds `rate_per_second` property for Camera storage stats (the existing value is actually bytes / millisecond)
* Adds support for `ustorage` field on NVR
* Adds missing enum values for `LightModeEnableType` and `LightModeType` (this _may_ be an unexpected change on the HA side)
> Fill out more fields accurately

- pyunifiprotect/api.py
- pyunifiprotect/cli/__init__.py
- pyunifiprotect/cli/base.py
- pyunifiprotect/cli/doorlocks.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
More CLI improvements from me trying to get the HomeKit functionality of the Door lock working (no luck).
* Adds CLI option to show unadopted devices
* Adds helper methods/CLI commands for adopting and unadopting devices
* Adds helper method and CLI command for calibrating Doorlocks
* Adds extra status text to `list-ids` if the device is in a special state
* Adds confirmation to rebooting devices via CLI
> Adds adopt/unadopt CLI

- pyunifiprotect/cli/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- tests/conftest.py
Nothing really new. Just updates from the new version. 
Also added fallback for display name for the `list-ids` command if the object has no name.
> Updates from UniFi Protect 2.1.1

- pyunifiprotect/data/__init__.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/bootstrap.py
- pyunifiprotect/data/convert.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- pyunifiprotect/data/user.py
- pyunifiprotect/utils.py
- tests/conftest.py
- tests/data/test_common.py
* Adds `Permission` model to parse permission strings from UniFi Protect
* Adds `can` method to user
* Adds `can_*` helper methods to Protect models to check permissions
* Splits all user related models into its own file, only the marked code sections are new for the `user.py`, the rest are moved from the old file.
Next PR will be to integrate the permissions into other locations/methods.
> Adds full handling of permissions

- pyunifiprotect/api.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/exceptions.py
- tests/data/test_common.py
* Adds `BadRequest` to making API requests
* Adds `revert_changes` method to base ProtectModel, will revert any unsaved changes to the model
* Updates `save_device` to automatically revert any changes made to the device if there was an error saving
* Adds permissions checks to various applicable places
* Not a breaking change these without this check, it would have raised a `NotAuthorized` error on trying to make the network request. The error has just been moved up to before the network request.
> Adds permission checking to various methods

- .vscode/launch.json
- pyunifiprotect/api.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/bootstrap.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/websocket.py
- pyunifiprotect/websocket.py
* Cleans up some no longer necessary and spammy WS debug messages
* Makes a few more fields optional (all from unadopted devices)
* Add support for "remove" WS messages so the full adopt/unadopt lifecycle can be subscribed to.
* This requires a backing change to the schema of `WSSubscriptionMessage` as `new_obj` can now be `None` for remove packets
The "lifecycle" of a device looks like the following:
* **Device Discovered** - WS packet add -> {model}
* **Device Adopted** - WS packet add -> event[deviceAdopted] with metadata of the `device_id` referencing previously discovered device 
* **Device Unadopted** - WS packet add -> event[deviceUnadopted], followed by WS packet remove -> {model}
> Cleans up WS logging. Adds support for remove WS messages

- dev-requirements.txt
- pyunifiprotect/data/base.py
- requirements.txt
I tried using `typing_extensions.Self`, but it kept raising errors about it not being a valid type. The error looks like it got fixed in 4.0.1, but still was having it in 4.2.0. 
This is a lot dirtier, but hopefully should be able to be cleaned up in the future once the Self stuff is actually fixed.
> Fixes copying update_lock

- pyunifiprotect/api.py
- pyunifiprotect/utils.py
- We can cache the lookup of the token and only look it up again when we know its invalid
> Speed up the is_authenticated check

- pyunifiprotect/api.py
- pyunifiprotect/data/bootstrap.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
* Ignore update packets for devices that do not exist
* Catch validation errors for WS packets and trigger a manual refresh of the device in the bootstrap (or ignore them for non-adoptable devices)
* Adds warning log message for using an EA version of UniFi Protect in Home Assistant
> Improve WS message processing

- pyunifiprotect/api.py
- pyunifiprotect/utils.py
We were seeing auth errors when the time wasn't perfectly in sync.
We now have a 60s safety to ensure we get a new token
We also only get one at time in case there are many requests that need one.
We now also handle the case were the http server disconnects.
> Handle auth failures when time is not perfectly in sync

- pyunifiprotect/cli/backup.py
* Adds page size for how many events are fetched back out of sqlite database at once (looks like sqlite cannot do streaming responses due to no server-side cursors, defaults to 1000 items)
* Adds length cutoff for identifying and skipping abnormally long events (defaults to 1 hour, which may already be too long)
* Replaces semaphore with a queue that tasks are pushed into. Queue is processed by a new download watcher task that ensures each task is completed without error or retries it. Adding new download tasks is paused when an error occurs until it is resolved.
> Improve backup reliability and memory usage

- dev-requirements.txt
- pyunifiprotect/cli/backup.py
- requirements.txt
- setup.cfg
* Adds `dateparser` requirement
* Allows human readable/relative datetime parsing from command line for start/end on backup events command (really useful if you want to put it on a cron)
> Adds relative datetimes for backup start/end

- dev-requirements.txt
- pyproject.toml
- pyunifiprotect/cli/backup.py
- requirements.txt
- setup.cfg
* Handle camera renames for files on disk
* Adds verification of files on disk using ffmpeg/pillow. Since this takes significantly longer to do, it is a flag that must be passed to complete it
Had to tweak the threshold for what is consider a "valid" video export since they vary so much. It looks 80% (18 seconds of a 22 second event) of the original event length seems to be the best. From sampling my events on my UNVR Pro, any event under 80% length has parts of the video missing.
> Adds file verification for backup

- dev-requirements.txt
- pyunifiprotect/cli/__init__.py
- pyunifiprotect/cli/backup.py
- pyunifiprotect/cli/events.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/utils.py
- requirements.txt
- setup.cfg
* Adds new title value for the file context that is used for writing video metadata by default
* Adds metadata to video files, metadata includes creation time/year/release and the a human friendly title for the file. Title can be controlled by the new `--title-format` parameter. Defaults to `"{time_pretty_local} {sep} {camera_name} {sep} {event_type_pretty} {sep} {length_pretty}"`
* Adds plenty of new fields for file contexts for setting templates for title/output files, including a lot of `_local` fields so you can save files in the same timezone as the camera
* Runs verification/metadata operations in a separate thread
* Removes pytz as a main dep since `zoneinfo` is python 3.9+
Note: ideal format for Plex to ingest exported files is:
```
--thumb-format …
```
> Adds metadata to backups and more file context

- pyunifiprotect/api.py
- pyunifiprotect/cli/backup.py
- pyunifiprotect/cli/events.py
- pyunifiprotect/data/nvr.py
* Adds `get_event_animated_thumbnail` and `get_animated_thumbnail` methods for API and Event objects
* Adds `save-animated-thumbnail` to events CLI
* Adds exporting animated thumbnails in events backup
* Adds option to disable thumbnail/animated thumbnail/video download in events backup
* Decreases the default number of download slots from 10 to 5 (animated thumbnail generation is hard on the NVR)
> Adds support for animated-thumbnail endpoint

- Dockerfile
- dev-requirements.txt
- docs/cli.md
- pyproject.toml
- requirements.txt
The needed timezone data for Python is not in the published docker image. Adds an optional extra that the docker image uses to ensure it is always there.
> Adds tzdata to docker image

- .vscode/launch.json
- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- tests/conftest.py
Updates for UniFi Protect 2.7.15:
* Adds `connectivity` field for WiFiConnectionState
* Adds `feature_flags` field for Chime
* Removes `avg_motions` field from NVR (this is technically a breaking change, but for some reason Protect removed the field in a bugfix version...)
* Updates for License Plate smart detection since 2.7.15 finally fixed/standardized it
> Updates for UniFi Protect 2.7.15

- pyunifiprotect/cli/chimes.py
- pyunifiprotect/data/bootstrap.py
- pyunifiprotect/data/devices.py
- tests/conftest.py
- tests/data/test_chime.py
* Adds new camera feature flag for `is_doorbell` and seperates functionality for `has_chime` and `is_doorbell`. There is an upcoming camera that has no transformer/chime support (G4 DBP PoE).
> Updates for UniFi Protect 2.7.18

- pyunifiprotect/data/devices.py
From discussion on this [HA issue](https://github.com/home-assistant/core/issues/83912) and bugging UniFi Protect devs, the intent of setting "Recording Mode" to "Never" is that the camera will not track anything. No motion events and footage. 
Updates all of the "is___detection_on" properties to take this into account and adds an `is_motion_detection_on` property to use for motion.
> Use Recording Mode for motion/smart status

- pyunifiprotect/data/devices.py
UniFi Protect started to make `/snapshot` and `/package-snapshot` default to a height of 360 if no width/height parameters were given. 
This overrides the behavior to always set a `h` query parameter of the max resolution if none are given. 
Fixes https://github.com/AngellusMortis/pyunifiprotect/issues/268
> Default snapshot to full resolution

- pyunifiprotect/data/nvr.py
Fixes #282 & https://github.com/home-assistant/core/issues/92984
This is enough that it allows the application to actually run locally, I have no idea if it'll fix the originally reported issue over on the [home-assistant/core](https://github.com/home-assistant/core) repo, but I can't see `wan_ip` being called anywhere so I imagine this field is ignored during normal operation.
> Fix IPv6 Behaviour

- pyunifiprotect/stream.py
Python 3.11 changed how enums are cast to strings.
> Fixes talkback stream in Python 3.11

- dev-requirements.txt
- pyproject.toml
- pyunifiprotect/cli/base.py
- pyunifiprotect/data/base.py
- pyunifiprotect/data/bootstrap.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- pyunifiprotect/data/user.py
- pyunifiprotect/utils.py
- requirements.txt
- tests/data/test_camera.py
- tests/data/test_chime.py
- tests/data/test_common.py
- tests/data/test_light.py
- tests/data/test_nvr.py
- tests/data/test_sensor.py
[Pydantic v2 bundled the v1 version with itself](https://github.com/pydantic/pydantic#pydantic-v110-vs-v2), so the first obvious step is to remove the constraint and allow v2 to be installed using the v1 API shim. 
It looks like a lot of the field internals changed so I will have to go back through each import, update them to allow the v2 version and test before we can use v2. It will likely be a breaking change (v5) to get pydantic v2 fully working as much of the "construct" logic may need to be removed or re-written.
> Add pydantic v1 shims to allow pydantic v2

- pyunifiprotect/data/bootstrap.py
- tests/test_api_ws.py
Adds `nvrMac` and `guid` to the list of keys we ignored as every message for a device attached to an nvr was generating a callback
> Strip unused keys in device updates to reduce state writes

- pyunifiprotect/test_util/__init__.py
- pyunifiprotect/utils.py
- tests/data/test_camera.py
Starting with Python 3.12 `datetime.utcnow` will be deprecated.
https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcnow
> Replace datetime.utcnow

- pyunifiprotect/data/base.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- pyunifiprotect/data/user.py
- pyunifiprotect/test_util/__init__.py
- tests/conftest.py
- tests/data/test_common.py
* New adopted item fields: `is_restoring`, `last_disconnect`, `anonymous_device_id` (was on many devices, but now on all)
* New camera recording settings: `in_schedule_mode` and `out_schedule_mode`
* New camera feature flags: `has_color_lcd_screen`, `has_line_crossing`, `has_line_crossing_counting`, `has_liveview_tracking`
* New Camera field: `has_recordings`
* New Chime feature flag: `has_https_client_ota`
* New NVR feature flags: `detection_labels` and `has_two_way_audio_media_streams`
* New NVR fields: `hard_drive_state`, `is_network_installed`, `is_protect_updatable`, `is_ucore_updatable`
* New events: `factoryReset`, `doorAccess`, `corruptedDbRecovered`, `applicationUpdatable`, `globalRecordingModeChanged`
* New video modes: `sport` and `slowShutter`
* New recording mode: `schedule` …
> Updates for Protect 2.9.20

- pyunifiprotect/cli/cameras.py
- pyunifiprotect/data/devices.py
- tests/data/test_camera.py
Added support to control whether or not Color Night Vision is enabled.
Note: Two tests are currently failing. I tried a few things to get them passing but not sure what I'm missing. If you let me know what I need to do, I'm happy to update this PR.
This addresses: https://github.com/AngellusMortis/pyunifiprotect/issues/303
Fixes the previous PR (https://github.com/AngellusMortis/pyunifiprotect/pull/318) without a valid commit, and hoping it fixes the tests otherwise.
> Add the ability to toggle Color Night Vision

- pyunifiprotect/cli/__init__.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- tests/conftest.py
Updates for UniFi Protect 2.10.10. Still need to update to UniFi OS 3.2 and test it as well. May make that a separate PR for that.
* Makes backup CLI not load if `backup` extra is not install. Fixes https://github.com/AngellusMortis/pyunifiprotect/issues/313
* Adds Camera feature flags for `has_flash` and `is_ptz` 
* Adds Camera field for `is_ptz`
* Changes `healthy` on UOS storage devices to `bool | str`
* Adds `size` field to UOS storage info
* Adds new events for `MULTIPLE_DEVICE_UPDATABLE`, `DEVICE_DISCONNECTED` and `NETWORK_DEVICE_OFFLINE`
> Updates for Protect 2.10.10

- pyunifiprotect/utils.py
- tests/conftest.py
- tests/sample_data/sample_camera.json
Protect is emitting an invalidly formatted UUID that is causing Python's native UUID type to throw an exception. This should handle the edge case.
> Fixes broken UUID from Protect

- pyunifiprotect/api.py
I have the issue as reported in #320 and upon some digging I noticed that the call to /login returned a 401 error after 2 hours as the old expired token was sent together with the credentials.
A retry mechanism ensures the login is done again and this works so there's no real interruption but still throws an exception.
The cookie jar is cleared for the /login call but the expired cookie needs to be removed from the HTTP headers too for this to work.
After the code change the logs stay clean and no more exceptions are logged related to the login. 
I created a new PR for a clean integration with signed commits and black/ruff checked.
> Clear cookies upon reauthenticate

- pyunifiprotect/data/types.py
To better guard against unknown values from protect, any enum that already has an "unknown" value will have their value set to unknown if an unlisted value is passed in.
> Automatically set enums to unknown for ones that support it

- pyunifiprotect/data/types.py
tuples are stored as constants in the code object so they do not get recreated every time this function is called. It would have been faster to decorate it with `@cached_property` and make it a property except `@cache_property` has an undocumented class instance lock which would have made it not viable until they fixed it in py 3.12 (maybe not a problem in this instance, but I wanted to go for a simple change here)
> Make bootstrap_models a tuple

- .devcontainer/devcontainer.json
- pyunifiprotect/data/__init__.py
- pyunifiprotect/data/devices.py
- pyunifiprotect/data/nvr.py
- pyunifiprotect/data/types.py
- tests/conftest.py
Just a first pass because I have to expose all of these on objects as well. 
Updates for UniFi Protect 2.11.13:
* Adds `retention_duration`, `smart_detect_post_padding`, `smart_detect_pre_padding` recording settings for cameras
* Adds `audio_style` and `has_vertical_flip` feature flags for cameras
* Adds `audio_settings` for cameras
* Adds `detected_thumbnails` support for Events
* Adds `last_device_fw_updates_checked_at` for NVR
* Adds new event and smart detection enums (will be exposed on camera objects in follow up)
> Updates for Protect 2.11.13

- pyunifiprotect/data/devices.py
- pyunifiprotect/data/types.py
Adds Camera helpers for all of the new event types.
I was thinking about reworking how tracking events for an event worked but decided not to. I did refactor out some shared logic to reduce code re-use for all of the new audio detection types. It moves some of the logic that was HA only into pyunifiprotect so the logic in HA will become more simple. 
While new code was added for the detected thumbnails, which includes things like the type of animal detected and/or the color/type of vehicle detected. Unfortunately, all of that data is only available post event, so it will not be usable inside of Home Assistant at all unless we duplicated _all_ of the sensors to have a "previous detected vehicle" sensor or something.
> Adds all new event types from Protect 2.11

- pyunifiprotect/data/devices.py
`leakDetectedAt` is reset to `null` when it is no longer detecting a leak. That also means you cannot have a `last detected leak` value as well.
> Adds leak sensor helper

- docs/cli.md
- pyunifiprotect/cli/cameras.py
- pyunifiprotect/data/devices.py
- tests/data/test_camera.py
The HTTP request for turning PTZ Auto Tracking simply modifies the smart detect settings of the cam.
For turning on:
"body": "{\"smartDetectSettings\":{\"autoTrackingObjectTypes\":[\"person\"]}}",
"method": "PATCH",
For turning off:
"body": "{\"smartDetectSettings\":{\"autoTrackingObjectTypes\":[]}}",
"method": "PATCH",
I dont know why its done like this, maybe they plan on enabling auto tracking on other objects than persons in the future. 
Ive added the simple functionallity to control auto track with the cli.
> add ptz auto tracking

- pyunifiprotect/api.py
- tests/test_api.py
Passing URL objects avoids having to have aiohttp create them each request Its a tiny speed up to getting camera snapshots
> Use URL objects for aiohttp requests

- pyunifiprotect/data/devices.py
`is_smart_detected` is never turned on for audio events.
> Fixes audio event detection helpers

- pyunifiprotect/api.py
- pyunifiprotect/cli/base.py
- pyunifiprotect/cli/chimes.py
- pyunifiprotect/data/devices.py
- tests/data/test_chime.py
* Adds `repeat_times` and `volume` options to `play_speaker` / `play` for API / Chime obj / CLI
trackNo not added yet since there are no alternative tracks or ways to add them.
> Add volume/repeat to play for chime

- dev-requirements.txt
- pyproject.toml
- pyunifiprotect/api.py
- pyunifiprotect/cli/__init__.py
- requirements.txt
Something I have wanted to support for a file since UniFi OS gets funky and returns 401 as a rate limit sometimes. 
* Adds `platformdirs` for getting the correct user cache / config directories
* Stores and loads `TOKEN` cookies to disk so `ProtectApiClient` can have persistent sessions. If you run `unifi-protect` 5-10 times rapidly, it will not randomly get a 401 since it does not issue a login each time. 
* Refactors how headers are handed so `cookie` / `x-csrf-token` are not randomly accidently deleted
* Fixes deprecation warning in CLI interface (replace `asyncio.get_event_loop` with `asyncio.run` for newer versions of Python)
* Set `x-csrf-token` on every request
This will require a HA side change to redirect the config directory to correct location.
> Add persistent sessions

- LICENSE
- LICENSE.CHANGE
- pyproject.toml
I have put a lot of thought into this and decided to make this change to protect this project from outside sources. As a result, I am purposing of changing the license from MIT to BUSL-1.1.
For nearly all possible use cases, I want to make it very clear, this project is **still** MIT. Anyone that wants to make derivative works or use the project may do so.
The license is being changed to BUSL to prevent the two following use cases:
Internally for development, for tooling, or for documentations or recommendations to users. Ubiquiti has been increasingly hostile towards local only access. They are so insistent on trying to create a facade they support "local only", but then lock more things behind Remote Access and their cloud. As long as they want to try to gaslight the community and keep …
> Change license from MIT to BUSL-1.1
