AngellusMortis/pyunifiprotect

pyunifiprotect/unifi_protect_server.py
My protect server saw a cpu spike and was a few
degrees warmer after installing the unifiprotect
integration due to the frequent polling.  When there
are >10 cameras this problem is much worse.
The bootstrap api is an expensive api to run
every 2s, which is the current update interval.
The calls to bootstrap are enough to have
a measurable impact on the event loop
The events api is rather cheap so its not a concern.
=> Only update cameras detail every 60s (Keep events at every 2s)

pyunifiprotect/__init__.py, pyunifiprotect/unifi_protect_server.py, websocket_test.py
Thanks to @hjdhjd for decoding the protocol
Fixes https://github.com/briis/pyunifiprotect/issues/4
here: https://github.com/hjdhjd/homebridge-unifi-protect/blob/master/docs/ProtectAPI.md?rgh-link-date=2020-09-08T14%3A30%3A43Z
=> Add websocket support

pyunifiprotect/unifi_protect_server.py, websocket_test.py
Allows updating the switch state right away
=> Add the ability to force a camera update

pyunifiprotect/unifi_protect_server.py
I ran the code though `black` and `pylint` (there are still a lot of items to address)
=> Guard websocket updates

pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py
I broke apart the data process into `unifi_data.py` as `pyunifiprotect/unifi_protect_server.py` was starting to get a bit large.
=> Refactor to reduce pylint errors

pyunifiprotect/__init__.py, pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py, websocket_test.py
If a motion event happened between when the doorbell was
rung and the events were fetched, the doorbell would
not be triggered
=> Ensure doorbell events are not missed when using websockets

pyproject.toml, pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py
In the original version, websocket events caused a poll to the
events api.  The events are now fully constructed from the websocket
add/update messages.
Fixes https://github.com/briis/unifiprotect/issues/139
=> Construct events from websocket updates

pyunifiprotect/unifi_protect_server.py
I couldn't replicate the issue in https://github.com/briis/pyunifiprotect/pull/11#issuecomment-727761135
However if the problem is what I think it is, this should fix the event not being reset on the first event after initial load.
For testing:
I left the events viewer up at in the protect web ui.  I verified the event cleared
when the event finished in the events view in the protect web ui.
Verified this works when restarting while an event is happening.
=> Skip event get if websocket is reconnecting

pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py
Work in progress
First step to support updating the camera data live so we can know when to switch from using events to the camera model when recording is turned off to see motion.
=> Update cameras model live from the websocket

pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py
Fixes https://github.com/briis/unifiprotect/issues/146
=> Always turn off events on end

pyunifiprotect/unifi_protect_server.py
The api in 1.17+ now shows non-adopted cameras / cameras on from other controller.
Note: I had to delete the extra "None" entities manually.
=> Ignore cameras that are not adopted to the controller

pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py
Still missing services to:
* Turn on/off the light
* Set brightness
* Set motion mode
=> Add initial support for Floodlight

pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py
Still missing the Services to change things on the Floodlight, but wanted to agree on structure first.
=> Moved to device vs. camera

pyunifiprotect/const.py, pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py
Should fix other cases of https://github.com/briis/unifiprotect/issues/181
Fix unique id not being unique
Run code though black and isort
=> Fix first update race condition

.github/workflows/ci.yaml, pyunifiprotect/__init__.py, pyunifiprotect/unifi_protect_server.py, requirements_all.txt, requirements_test.txt, setup.py, tests/test_unifi_protect_server.py, tox.ini
https://github.com/bdraco/pyunifiprotect/actions/runs/534836772
We can give some basic feedback if there is a problem
=> Setup a basic CI

pyunifiprotect/unifi_protect_server.py
When we called back the subscribers in fire_event we only
sent the changes. Sometimes this would be missing event_on
or event_ring_on if the websocket connected before the
integration setup the binary sensor. We now always return
the full processed data.
Should fix the last case of https://github.com/briis/unifiprotect/issues/181
Various cleanups (there were too many things called `data` to keep track of)
=> Ensure websocket updates always contain the full processed data

protectdata_function.py, pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py
=> feat(g4doorbell/chime_duration): make chime duration adjustable

pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py
Fixes https://github.com/briis/unifiprotect/issues/270
=> Allow requesting a custom snapshot width and height

pyunifiprotect/cli.py, pyunifiprotect/test_util/__init__.py, pyunifiprotect/test_util/anonymize.py, pyunifiprotect/unifi_data.py, pyunifiprotect/unifi_protect_server.py, requirements_all.txt, requirements_test.txt, setup.cfg, tox.ini
* Adds mypy and other `types-*` libraries for third packages already used
* Fixes all typing lint errors
=> Adds mypy linting

pyunifiprotect/data/types.py
New event I found from upgrading. Looks like there is no other new data from `beta.7`.
=> Adds applicationUpdate event

pyunifiprotect/data/__init__.py, pyunifiprotect/data/base.py, pyunifiprotect/data/bootstrap.py, pyunifiprotect/data/convert.py, pyunifiprotect/data/nvr.py, pyunifiprotect/unifi_protect_server.py
Followup for https://github.com/briis/pyunifiprotect/pull/75#discussion_r741952875
=> Refactor to avoid late imports

pyunifiprotect/data/devices.py, pyunifiprotect/data/nvr.py, pyunifiprotect/test_util/__init__.py, tests/conftest.py, tests/sample_data/sample_constants.json, tests/test_unifi_protect_server_old.py
Migrated from UDM-Pro to UNVR-Pro. Some minor updates to support my new instance. Looks like most of them are just some unexpected defaults when there are no values (storage capacity/last login/etc).
=> Updates from migrating to UNVR-Pro

tox.ini
=> Fixes running tests for ci

tests/conftest.py
Refactors @bdraco mentioned.
I am not sure why it is complaining about assigning to "Cannot assign to a method" now for the replacing the methods. I also cannot find a proper error code for that either to disable it via config since it is pretty common in tests.
=> Simplifies creating test API clients

pyunifiprotect/api.py, pyunifiprotect/data/base.py, pyunifiprotect/data/nvr.py
Some updates for docs strings.
=> Updates some doc strings

pyunifiprotect/data/devices.py, tests/test_api.py, tests/test_data_updates.py
Calculated feature flag to make the switch on the HA easier to do.
=> Adds has_highfps calculated feature flag

pyunifiprotect/data/base.py, pyunifiprotect/data/types.py
`last_seen` is None when device is connecting.
=> More fixes for failing tests

.github/workflows/ci.yaml
* Updates CI workflow to only run-on master for push (removes the duplicate GHA runs for PRs)
=> Prevents duplicate workflow runs

pyproject.toml, pyunifiprotect/data/bootstrap.py, pyunifiprotect/utils.py, tests/test_api_ws.py
* Adds a lot more keys to be filtered for stats
* Adds way to capture packet metadata to print out summary of processed packets over the course of a period of time:
```
------------------------------- ws stat summary -------------------------------
packet count: 84
filtered packet count: 20 (76.19%)
--------------------------------------------------------------------------------
event: 10
camera: 9
light: 1
--------------------------------------------------------------------------------
update: 14
add: 6
--------------------------------------------------------------------------------
score: 9
last_motion: 9
end: 8
smart_detect_event_ids: 8
model: 6
id: 6
type: 6
start: 6
heatmap_id: 6
camera_id: 6
--------------------------------------------------------------------------------
```
=> Adds packet profiling

.devcontainer/devcontainer.json, pyunifiprotect/data/__init__.py, pyunifiprotect/data/bootstrap.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/nvr.py, pyunifiprotect/data/websocket.py, pyunifiprotect/utils.py, tests/test_data.py
Changes to make type enforcement in `unifiprotect` better
* Adds more items to `data/__init__.py` to prevent using submodules
* Removes all outward facing pydantic validator types
* Changes `WSSubscriptionMessage` to `ProtectModelWithId`
=> Improves outward facing types

pyunifiprotect/data/devices.py, tests/test_data_updates.py
* `Lights`: adds `set_paired_camera`
=> Adds set_paired_camera helper method to lights

pyunifiprotect/data/devices.py, tests/test_data_updates.py
* `Camera`: adds properties for `is_person_detection_on` and `is_vehicle_detection_on`
* `Camera`: adds `set_system_sounds`, `set_osd_name`, `set_osd_date`, `set_osd_logo`, `set_osd_bitrate`, `set_smart_detect_types`, `set_person_detection`, `set_vehicle_detection` helper methods
=> Adds various new camera helpers

pyunifiprotect/stream.py
This gets talkback to work on G4 Doorbell and G4 Dome. Looks like the issue was setting the quality.
=> Fixes bitrate for talkback

pyunifiprotect/api.py, tests/test_api.py
Not really easy to test this one, but hopefully the new unit test should handle it.
=> Fixes pre-1.20 record mode error

tests/conftest.py
=> Fixes check against unexpected metadata keys for events

pyunifiprotect/api.py, pyunifiprotect/data/base.py, pyunifiprotect/data/nvr.py, pyunifiprotect/utils.py, tests/test_api.py, tests/test_data.py
Fixes https://github.com/briis/unifiprotect/issues/431
=> Allows DNS hosts for NVR hosts or device host

pyunifiprotect/data/base.py, pyunifiprotect/data/bootstrap.py, pyunifiprotect/data/devices.py, tests/test_api_ws.py
* `Camera`: Adds `is_ringing` property
* `Sensor`: Adds `is_tampering_detected` and `is_alarm_detected` properties
Probably need something similar for leaks, but until we get the leak stuff, I cannot verify how it works.
=> Adds boolean for chime ring, sensor tamper and alarm

pyunifiprotect/api.py
More stuff to try to improve reconnect:
* Lower Websocket reconnect interval to 30 seconds
* Use `create_task` instead of `ensure_future`, following the recommendation of the Python docs
* More logging so we know right away when the new task is scheduled
=> Tweaks for websocket reconnect

pyunifiprotect/cli.py, pyunifiprotect/test_util/__init__.py, pyunifiprotect/utils.py
Port change from 1.x branch. Just CI check.
=> Makes IO async friendly. Adds profile_ws command. Add zip option to data gen

pyunifiprotect/data/devices.py, pyunifiprotect/data/types.py, tests/conftest.py, tests/sample_data/sample_camera.json
* `Camera`: Adds `chime_type` to mirror how the Chime settings in the UI works. 
* `Camera`: Adds support for package camera from G4 Doorbell Pro.
=> Chime type. G4DBP

pyunifiprotect/api.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/types.py, tests/conftest.py, tests/sample_data/sample_camera.json
More backports from 2.x. Just a CI check.
=> More backports

pyunifiprotect/data/bootstrap.py, pyunifiprotect/data/devices.py, setup.cfg, tests/conftest.py
=> Updates from UniFi Protect 1.21-beta3 (#156)

pyunifiprotect/data/devices.py, pyunifiprotect/data/types.py, setup.cfg
Port from 1.x. Just waiting for CI.
(I really hope this is the last time this is needed, lol)
=> Fix MECHANICAL spelling. Add is_package to camera channel (#158)

pyunifiprotect/api.py, pyunifiprotect/data/devices.py, tests/test_api.py
Package camera uses a different snapshot URL.
=> Adds get_package_snapshot to camera for package camera snapshots

pyunifiprotect/api.py, pyunifiprotect/data/devices.py, tests/test_api.py
Just backporting PR from master branch so it can be added to HA. Waiting a CI check.
=> Adds get_package_snapshot to camera for package camera snapshots (#162)

pyunifiprotect/api.py, pyunifiprotect/websocket.py
* Force re-auth on multiple reconnect failures
* Log Websocket exceptions
* Ensure only a single connection attempt is ever made
* Improves disconnection/reconnect log messages
* Fix timeout if Websocket connect fails
=> More Websocket improvements

pyunifiprotect/data/base.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/nvr.py, pyunifiprotect/data/types.py, tests/conftest.py, tests/test_api.py, tests/test_data.py
I intentionally did not update the sample data so we can still verify again the 1.21 versions.
=> Updates for 2.0-beta2

pyunifiprotect/cli/__init__.py, pyunifiprotect/cli/base.py, pyunifiprotect/cli/cameras.py, pyunifiprotect/cli/chimes.py, pyunifiprotect/cli/doorlocks.py, pyunifiprotect/cli/light.py, pyunifiprotect/cli/liveviews.py, pyunifiprotect/cli/nvr.py, pyunifiprotect/cli/sensors.py, pyunifiprotect/cli/viewers.py
* Adds `liveview` subcommand
* Adds validated to ensure device/devices are set correct on the context
* Fills out subcommands for all of the helper methods for `chime`, `doorlock`, `light` and `viewer` objects (still missing are sensor and camera)
=> Adds second round of commands for UFP devices

pyunifiprotect/data/bootstrap.py, tests/test_api.py
Adds `get_device_from_mac` to bootstrap to look up devices by MAC address.
=> Adds MAC address lookup

pyunifiprotect/cli/base.py, pyunifiprotect/cli/sensors.py
* Captures validation errors in `run` helper and prints them out (so there is no stack trace).
* Adds sensor subcommands.
=> Adds sensor subcommands

pyunifiprotect/cli/base.py, pyunifiprotect/cli/nvr.py, pyunifiprotect/data/base.py
* Adds `set_name` helper 
* Adds `set-name` and `update` commands for all devices
=> Adds more helpful commands

pyunifiprotect/cli/__init__.py, pyunifiprotect/cli/base.py, pyunifiprotect/cli/cameras.py, pyunifiprotect/cli/events.py
* Adds events CLI
* Make sure user provided datetimes are always localized correctly
=> Adds events cli

README.md, pyunifiprotect/data/base.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/nvr.py
More from the Protect backend. Do not let certain fields be changed.
=> Initial read only enforcement for fields

pyunifiprotect/api.py, pyunifiprotect/data/bootstrap.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/nvr.py, pyunifiprotect/data/types.py
Some followups needed for HA:
* Allows passing an iterator callback for streaming responses to pass a chunk at a time
* Adds `has_doorbell`, `recording_start` and `has_smart_detections` computed properties for Bootstrap
* Adds `has_disk` and `is_healthy` for UOSDisks
=> Updates needed for HA

pyunifiprotect/data/base.py
Changes discussed in https://github.com/home-assistant/core/pull/73722
=> Revert some changes for performance

pyunifiprotect/data/bootstrap.py
A couple of more helpers for HA media sources
=> Adds has_media helper method

pyunifiprotect/data/base.py, pyunifiprotect/data/user.py, tests/data/test_common.py
* Adds support for a permission string that has multiple obj IDs
* Adds support for the "self" permission identifier (`$`) for user permissions
=> Fix permissions issue

pyunifiprotect/cli/base.py, pyunifiprotect/data/base.py, pyunifiprotect/data/bootstrap.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/nvr.py
* Adds `display_name` which is like name, but always returns some string value
* Adds `get_device_from_id` to look up unknown devices by ID efficiently, similar to MAC lookup
* Adds code so the MAC lookups will automatically update over time as devices are added/removed
* Adds `is_high_fps_enabled` helper for cameras
* Adds `is_adopted_by_us` helper
=> More helpers for HA

dev-requirements.txt, pyunifiprotect/api.py, pyunifiprotect/cli/__init__.py, pyunifiprotect/cli/base.py, pyunifiprotect/cli/nvr.py, pyunifiprotect/data/websocket.py, requirements.txt, setup.cfg
=> Switch json encoder/decoder to orjson

pyunifiprotect/data/base.py, pyunifiprotect/data/devices.py
Adds more optional values that get nulled when (un)adopting.
=> More optional values

pyunifiprotect/data/base.py
https://github.com/samuelcolvin/pydantic/blob/228e46de35910d5caed504c48b71900fef1d2b8a/pydantic/main.py#L821
Similar to https://github.com/briis/pyunifiprotect/pull/198
=> Use pydantic dict fast path for update_from_dict

dev-requirements.txt, pyunifiprotect/data/base.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/nvr.py, requirements.txt, setup.cfg, tests/data/test_common.py
* Adds `queue_update` method that pushes an update onto a queue and then waits for others updates to come in (50 ms). Will automatically cancel if one does. Only the last remaining `queue_update` will then acquire the update lock and call `save_device`
* Updates all of the helper methods to use the new `queue_update` method
=> Aggregate updates to reduce PATCH requests/locking

dev-requirements.txt, pyunifiprotect/cli/__init__.py, pyunifiprotect/cli/backup.py, pyunifiprotect/cli/cameras.py, pyunifiprotect/cli/chimes.py, pyunifiprotect/cli/doorlocks.py, pyunifiprotect/cli/events.py, pyunifiprotect/cli/light.py, pyunifiprotect/cli/liveviews.py, pyunifiprotect/cli/nvr.py, pyunifiprotect/cli/sensors.py, pyunifiprotect/cli/viewers.py, requirements.txt, setup.cfg
typer>0.6 adds integration with the popular library [rich](https://github.com/Textualize/rich). This fully integrates rich. Notably:
* Rich color formatting can be used in doc strings now for help messages
* Replaces click/typer progress bar with rich one
Some images:
=> Use rich integration for typer

pyunifiprotect/data/bootstrap.py, pyunifiprotect/data/nvr.py
Just moves `get_is_prerelease` to the NVR object.
=> Adds is_prerelease to NVR

pyunifiprotect/cli/cameras.py, pyunifiprotect/data/base.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/nvr.py, pyunifiprotect/data/types.py, pyunifiprotect/utils.py, tests/conftest.py
* CLI - Adds `smart-audio-types` subcommand for cameras to manage detection types for audio smart detections
* WifiConnectionState - New fields - `ap_name` and `experience`
* All adoptable devices - New fields - `fw_update_state`
* Camera
* New Fields - `is_waterproof_case_attached` and `last_disconnect`
* Enable SmartAudioDetect support
* Event
* New Fields - `deleted_at` and `deletion_type`
* New Metadata field - `license_plate`
* New Events - `POOR_CONNECTION`, `STREAM_RECOVERY`, `SMART_AUDIO_DETECT`, `CONSOLIDATED_RESOLUTION_LOWERED` and `CONSOLIDATED_POOR_CONNECTION`
=> Updates for Protect EA 2.7.5

pyunifiprotect/websocket.py
Noticed this does not need to be a coro while
investigating an unrelated issue.
=> Make _reset_timeout a normal function

pyunifiprotect/utils.py, tests/test_utils.py
related issue #236 (not a full solution but an easy win)
=> Speed up to_snake_case

.github/workflows/ci.yaml, .github/workflows/docker.yml, .github/workflows/pypi.yml, Dockerfile, dev-requirements.txt, pyproject.toml, pyunifiprotect/cli/__init__.py, pyunifiprotect/cli/backup.py, pyunifiprotect/data/base.py, pyunifiprotect/data/bootstrap.py, pyunifiprotect/data/devices.py, pyunifiprotect/utils.py, pyunifiprotect/websocket.py, requirements.txt, tests/data/test_camera.py, tests/data/test_common.py
* Updates all requirements
* Fixes new mypy 1.0 errors
* Fixes typing support for sqlalchemy (they added official support in package)
* Adds official python 3.11 support.
* replaces and closes #265
=> Updates all requirements and add Python 3.11 support

pyunifiprotect/data/base.py, pyunifiprotect/data/bootstrap.py, pyunifiprotect/websocket.py, tests/test_api_ws.py
Fixes https://github.com/AngellusMortis/pyunifiprotect/issues/267
=> Fix weak refs

pyunifiprotect/data/base.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/nvr.py, pyunifiprotect/data/user.py
I've been looking for ways to reduce the run time of `update_from_dict` as its the single most expensive call on my HA instance:
Before:
After:
=> Cache static field construction

pyunifiprotect/cli/backup.py, pyunifiprotect/cli/events.py, pyunifiprotect/data/bootstrap.py, pyunifiprotect/data/nvr.py
At some point they actually fixed Crossing Line Events to be smartDetectLine events instead of smartDetectZone events. So this makes it so they both trigger "smart detections" correctly.
=> Improves smart detect line support

pyunifiprotect/data/base.py
fixes https://github.com/home-assistant/core/issues/92108
=> Fix missing read only fields exclude

pyunifiprotect/data/base.py, pyunifiprotect/stream.py, pyunifiprotect/utils.py, pyunifiprotect/websocket.py
related issue home-assistant/core#92341
=> Update asyncio wait and timeout for python 3.11

pyunifiprotect/utils.py
=> Fix performance regression in `convert_unifi_data` from IPv6 support

pyunifiprotect/data/devices.py
=> Cache construction of rtsp URLs

pyunifiprotect/utils.py
fixes #236 (along with all the previous changes)
=> Refactor convert_unifi_data and serialize_unifi_obj to improve performance

pyunifiprotect/data/devices.py
=> Adds set_event helpers for new events

pyunifiprotect/data/types.py
Add "readlive" permission introduced in Protect 3.0.10
=> Update types.py to add new live only role

pyunifiprotect/data/base.py
This is 90% of the run time at setup. After the change it doesn't show up on the profile anymore
=> Cache issubclass in _set_protect_subtypes

pyunifiprotect/cli/chimes.py, pyunifiprotect/data/__init__.py, pyunifiprotect/data/base.py, pyunifiprotect/data/devices.py, pyunifiprotect/data/types.py, tests/data/test_chime.py
* Add `set_repeat_times` and `set_repeat_times_for_camera` helper methods
* Adds `set_volume_for_camera` helper method
* Adds `set-repeat-times` command to Chime CLI
* Adds `set-volume` command for Chime CLI
=> Add support for repeat times for chime
